RestaurantEFDbFirstApproachCRUD/Models/Restaurant.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantEFDbFirstApproachCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int RestaurantId { get; set; }
        public string RestaurantName { get; set; }
        public string Cusine { get; set; }
    }
}

RestaurantEFDbFirstApproachCRUD/Models/RestaurantModel1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantEFDbFirstApproachCRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WFA3DotNetEntities : DbContext
    {
        public WFA3DotNetEntities()
            : base("name=WFA3DotNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Restaurant> Restaurants { get; set; }
    }
}

RestaurantEFDbFirstApproachCRUD/Models/RestaurantModel1.Designer.cs
// T4 code generation is enabled for model 'D:\DotNETBatch2021\Assignments\RestaurantAppMVCProject09Feb2021\RestaurantAppMVCProject\RestaurantEFDbFirstApproachCRUD\Models\RestaurantModel1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

RestaurantEFDbFirstApproachCRUD/Models/RestaurantModel1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

RestaurantEFDbFirstApproachCRUD/Controllers/HomeController.cs
using RestaurantEFDbFirstApproachCRUD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurantEFDbFirstApproachCRUD.Controllers
{
    public class HomeController : Controller
    {
        WFA3DotNetEntities db = new WFA3DotNetEntities();
        public ActionResult Index(string search="")
        {
            //ViewBag.Search = 
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

RestaurantEFDbFirstApproachCRUD/Controllers/RestaurantController.cs
using RestaurantEFDbFirstApproachCRUD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RestaurantEFDbFirstApproachCRUD.Controllers
{
    
    public class RestaurantController : Controller
    {
        WFA3DotNetEntities db = new WFA3DotNetEntities();
        // GET: Restaurant
        public ActionResult Index(string search="")
        {
            //var rest = db.Restaurants.ToList();
            var rest = db.Restaurants.Where(r => r.RestaurantName.Contains(search)).ToList();
            return View(rest);
        }

        //Show Restaurant Details
        public ActionResult ShowDetails(int id)
        {
            Restaurant details = db.Restaurants.Where(r=>r.RestaurantId==id).FirstOrDefault();
            return View(details);
        }

        //Create operation
        public ActionResult AddRecord()
        {
            ViewBag.Restau = db.Restaurants.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult AddRecord(Restaurant restaurant)
        {
            db.Restaurants.Add(restaurant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Edit 

        public ActionResult UpdateRecord(int id)
        {
            var restoUpdate = db.Restaurants.Where(r => r.RestaurantId == id).FirstOrDefault();

            return View(restoUpdate);
        }

        [HttpPost]
        public ActionResult UpdateRecord(Restaurant restaurant)
        {
            var restoUpdate = db.Restaurants.Where(r => r.RestaurantId == restaurant.RestaurantId).FirstOrDefault();
            restoUpdate.RestaurantName = restaurant.RestaurantName;
            restoUpdate.Cusine = restaurant.Cusine;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var delete = db.Restaurants.Where(r => r.RestaurantId == id).FirstOrDefault();
            return View(delete);
        }

        [HttpPost]
        public ActionResult Delete(Restaurant restaurant)
        {
            var delete = db.Restaurants.Where(r => r.RestaurantId == restaurant.RestaurantId).FirstOrDefault();
            db.Restaurants.Remove(delete);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Image()
        {
            return View();
        }
    }
}

RestaurantEFDbFirstApproachCRUD/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

RestaurantEFDbFirstApproachCRUD/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RestaurantEFDbFirstApproachCRUD/Views/Home/Index.cshtml
@model RestaurantEFDbFirstApproachCRUD.Models.WFA3DotNetEntities
@{
    ViewBag.Title = "Home Page";
}




@*<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

RestaurantEFDbFirstApproachCRUD/Views/Restaurant/AddRecord.cshtml
@{
    ViewBag.Title = "AddRecord";
}

<h2>AddRecord</h2>

<form action="/Restaurant/AddRecord" method="post">
    <div class="form-row">
        <div class="form-group col-md-10">
            <label for="RestaurantName">Restaurant Name</label>
            <input type="text" name="RestaurantName" class="form-control" id="RestaurantName" placeholder="Restaurant Name" />
        </div><br />
        <div class="form-group col-md-11">
            <label for="Cusine">Cusine</label>
            <select class="form-control" id="Cusine" name="Cusine">
                {
                <option value="">Please Select DeptId</option>
                <option value="Indian">Indian</option>
                <option value="Italian">Italian</option>
                <option value="French">French</option>
                }
            </select>
        </div>
        <div class="form-group col-md-10">
            <button type="submit" class="btn btn-success">Add Restaurant Details</button>
            <a href="/Restaurant/Index" class="btn btn-danger">Cancel</a>
        </div><br />
        
    </div>
    <br />
   
</form>

RestaurantEFDbFirstApproachCRUD/Views/Restaurant/Delete.cshtml
@model RestaurantEFDbFirstApproachCRUD.Models.Restaurant
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<form action="/Restaurant/Delete/@Model.RestaurantId" method="post">
    <div class="form-row">
        <div class="form-group col-md-10">
            <input type="hidden" name="RestaurantId" value="@Model.RestaurantId" />
            <label for="RestaurantName">Restaurant Name</label>
            @Model.RestaurantName
        </div><br />
        <div class="form-group col-md-10">
            <label for="Cusine">Cusine</label>
            @Model.Cusine
        </div>
        <div class="form-group col-md-6">
           <br /> <button type="submit" class="btn btn-danger">Delete Restaurant</button>
            <a class="btn btn-info" href="/Restaurant/Index">Cancel</a>
        </div><br />
    </div>
   
</form>

RestaurantEFDbFirstApproachCRUD/Views/Restaurant/Image.cshtml
@{
    ViewBag.Title = "Image";
}



<style>

    h2 {
        color: brown;
        font-family: 'Times New Roman', Times, serif;
        font-weight:bold;
        font-size:33px;
    }
</style>

<h2>Restaurant</h2>

<div>
    <div class="col-md-4">
        <table>
            <tr>

                <td><a href="/Restaurant/Index"><img src="~/Images/pizza.jpg" /></a></td>
                <td><img src="~/Images/dalBati.jpg" /></td>
                <td><img src="~/Images/indianfood.jpg" /></td>
            </tr>

            <tr>

                <td><img src="~/Images/pastaitalian.jpg" /></td>
                <td><img src="~/Images/french.jpg" /></td>
                <td><img src="~/Images/foodie.jpg" /></td>
            </tr>
        </table>
    </div>
</div>

RestaurantEFDbFirstApproachCRUD/Views/Restaurant/Index.cshtml
@model IEnumerable<RestaurantEFDbFirstApproachCRUD.Models.Restaurant>
@{
    ViewBag.Title = "Index";
}

<h2>Restaurant List</h2>
<br />
<a href="/Restaurant/AddRecord" class="btn btn-primary">Add Restaurant</a>

<br />
<form class="form-inline" action="/Restaurant/Index">
    <label for="search">SearchRestaurant</label>
    <input type="text" class="form-control" name="search" id="search" placeholder="Enter Restaurant Name"/>
   <button class="btn btn-info">Search</button>
</form>
<br />

<table class="table">
    <tr>
        <th style="font-weight:bold; font-size:20px;">Restaurant Name</th>
        <th>Cusines</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
    <td><a href="/Restaurant/ShowDetails/@item.RestaurantId">@item.RestaurantName</a></td>
    <td><a href="">@item.Cusine</a></td>
    <td><a href="/Restaurant/ShowDetails/@item.RestaurantId"class="btn btn-info">ShowDeatils</a></td>
    <td><a href="/Restaurant/UpdateRecord/@item.RestaurantId" class="btn btn-primary">Edit</a></td>
    <td><a href="/Restaurant/Delete/@item.RestaurantId" class="btn btn-danger">Delete</a></td>
    </tr>
    }
</table>

RestaurantEFDbFirstApproachCRUD/Views/Restaurant/ShowDetails.cshtml
@model RestaurantEFDbFirstApproachCRUD.Models.Restaurant
@{
    ViewBag.Title = "ShowDetails";
}

<style>
    th,td
    {
        font-size:20px;
        font-family:'Times New Roman';

    }
    h2 {
        font-size: 30px;
        font-family: 'Times New Roman';
        color:brown;
    }
</style>

<h2>Show Restaurant Details</h2>

<br />
<table class="table col-md-2">
    <tr>
        <th>Restaurant Name</th>
        <td>@Model.RestaurantName</td>
    </tr>
    <tr>
        <th>Cusine</th>
        <td>@Model.Cusine</td>
    </tr>
    
</table>

<a href="/Restaurant/Index" class="btn btn-info">Back</a>

RestaurantEFDbFirstApproachCRUD/Views/Restaurant/UpdateRecord.cshtml
@model RestaurantEFDbFirstApproachCRUD.Models.Restaurant
@{
    ViewBag.Title = "UpdateRecord";
}

<h2>UpdateRecord</h2>

<form action="/Restaurant/UpdateRecord/@Model.RestaurantId" method="post">
    <div class="form-row">
        <div class="form-group col-md-10">
            <input type="hidden" name="RestaurantId" value="@Model.RestaurantId" />
            <label for="RestaurantName">Restaurant Name</label>
            <input type="text" name="RestaurantName" class="form-control" id="RestaurantName" value="@Model.RestaurantName" />
        </div><br />
              <div class="form-group col-md-10">
                  <label for="Cusine">Cusine</label>
                  @*<input type="text" name="Cusine" class="form-control" id="Cusine" value="@Model.Cusine" />*@
                  <select class="form-control" id="Cusine" name="Cusine">
                      {
                      <option value="">Please Select DeptId</option>
                      <option value="Indian">Indian</option>
                      <option value="Italian">Italian</option>
                      <option value="French">French</option>
                      }
                  </select>
              </div>

        <div class="form-group col-md-6">
            <button type="submit" class="btn btn-success">Edit Restaurant</button>
            <a class="btn btn-info" href="/Restaurant/Index">Cancel</a>
        </div>
    </div>
   
</form>

RestaurantEFDbFirstApproachCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        .navcolor {
            background-color: #0f465f;
            font-size: 24px;
            font-family: 'Times New Roman';
            font-weight: bold;
           
        }
        
    </style>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-fixed-top navcolor">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Meet my Restaurant", "Index", "Restaurant", new { area = "" }, new { @class = "navbar-brand" })*@
            
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    @*@Html.ActionLink("Meet my Restaurant", "Index", "Restaurant")*@
                    <li>@Html.ActionLink("My Restaurant", "Image", "Restaurant")</li>
                    <li>@Html.ActionLink("Restaurant Detail", "Index", "Restaurant")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @*<img src="~/Images/dalBati.jpg"/>*@
        @RenderBody()
        <hr />
        <footer class="navbar-fixed-bottom navbar-inverse">
            <p style="font-weight:bold; color:burlywood; font-size:20px;">&copy; @DateTime.Now.Year - My Restaurant</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>